name = "ai-news-wechat-share"
main = "cloudflare-worker-wechat-share.js"
compatibility_date = "2024-01-01"

# 路由配置 - 只处理微信相关请求
routes = [
  { pattern = "news.aipush.fun/*", custom_domain = true }
]

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"
ORIGIN_URL = "https://news.aipush.fun"

[env.staging.vars]
ENVIRONMENT = "staging"
ORIGIN_URL = "https://news.aipush.fun"

# KV存储（用于缓存新闻数据）
[[kv_namespaces]]
binding = "NEWS_CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
