// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtyfmcxyfmukhwupsrvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eWZtY3h5Zm11a2h3dXBzcnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTAyMTksImV4cCI6MjA2OTcyNjIxOX0.mHJ6MpQJZ8PxokdmOQ3Uanx2S0wJckE6ZO8tpt2xnqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});